name: Deploy in heroku

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy heroku
        uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: ${{secrets.HEROKU_KEY}}
          heroku_app_name: "dreambank-danielgz"
          heroku_email: "dagoza01@gmail.com"
          buildpack: "https://github.com/devmynd/heroku-buildpack-angular-spa.git"
